### ISSUE TITLE
Instrumentation fails to create directories

### ISSUE THREAD

**Issue by ghost** [attekett/NodeFuzz#4]
Instrumentation fails linux and firefox:

Symbolizing
Filting
parsing
/home/agar/NodeFuzz/instrumentations/instrumentation_linux_asan.js:35
        throw e;
        ^

Error: ENOENT: no such file or directory, stat '/home/agar/NodeFuzz/results//folders/firefox-on-interceptorstrlen'
    at Error (native)
    at Object.fs.statSync (fs.js:1000:11)
    at mkdirsSync (/home/agar/NodeFuzz/instrumentations/instrumentation_linux_asan.js:24:22)
    at /home/agar/NodeFuzz/instrumentations/instrumentation_linux_asan.js:171:4
    at FSReqWrap.oncomplete (fs.js:123:15)

Tried to create by hand those directories but keep failing any time that crashes. Should I change something?.

Another topic, is it possible to use a database like mongodb to use code fragments as a module? Async issues due the nature of NodeFuzz?

**Comment by agarciagonzalez** [comment]
@attekett help please

**Comment by attekett** [comment]
Hi,

Which nodejs version are you using and on which Linux distro? Can you add a print to see the value of e.errno before instrumentation_linux_asan.js:35? It should be "34" and go inside the if-statement with ENOENT. 

It is possible to add async functionality in to the test case generators. If your test case generator .fuzz() function returns an empty string, NodeFuzz will wait for 50ms and ask again, so just return empty string until your async operation has finished and the test case is ready.

**Comment by agarciagonzalez** [comment]
node v6.11.2, Ubuntu 16.04.3 LTS. Do you mind to share an async code snippet? I'm sure a lot of people will be worth the example. I'll try to print e.errno when fail again

**Comment by agarciagonzalez** [comment]
output when crash

 errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: './results/folders/firefox-(0x0000053c8aa0):-asanregisterglobalspart11' }
{ Error: ENOENT: no such file or directory, stat './results/folders/firefox-(0x0000053c8aa0):-asanregisterglobalspart11'
    at Error (native)
    at Object.fs.statSync (fs.js:1000:11)
    at mkdirsSync (/home/agar/NodeFuzz/instrumentations/instrumentation_linux_asan.js:24:22)
    at /home/agar/NodeFuzz/instrumentations/instrumentation_linux_asan.js:172:4
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by attekett** [comment]
Did you get the ASAN trace from that case? Looks like parser returned some illegal characters for the file name, could be that it got only partial trace. You should add filtering to remove '(', ':', ')'.

In the first case the path looks sane. ENOENT error code should be 34, but in your case it is -2. Try to switch the "e.errno == 34" to "e.code == 'ENOENT'".

**Comment by attekett** [comment]
No activity in few years. I presume that this is not an issue anymore.
